# Generated by Django 4.2.2 on 2023-07-04 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'home', 'verbose_name_plural': 'categories'},
        ),
    ]
