# Generated by Django 4.2.2 on 2023-06-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_search_else'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search_else',
            name='msg',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
